# Overview

Transform 1 and 2-dimensional data in Python Lists and Dictionaries into Numpy Arrays, Apply reshape, join, and split operations to Numpy arrays, and Apply aggregate functions like mean, average, product, median, standard deviation, variance to Numpy arrays leveraging the real world data of the Lakers starting players to calculate their BMIs. 

In [35]:
# Import libraries

import numpy as np
import json

In [36]:
# Read the data 

with open('./data.json','r', encoding='utf-8') as f:
    bmi_data = json.loads(f.read())
    
with open('./efficiency_data.json','r', encoding='utf-8') as f:
    stats_data = json.loads(f.read())

In [124]:
# Get the height of the Lakers  

lakers_height = [value for data in bmi_data["Lakers"] for key, value in data.items() if key=="Height"]
lakers_weight = [value for data in bmi_data["Lakers"] for key, value in data.items() if key=="Weight"]

In [68]:
# Get the stats data for the Lakers

pts = [value for data in stats_data["Lakers"]for key, value in data.items() if key=="PTS"]
reb = [value for data in stats_data["Lakers"]for key, value in data.items() if key=="REB"]
ast = [value for data in stats_data["Lakers"]for key, value in data.items() if key=="AST"]
stl = [value for data in stats_data["Lakers"]for key, value in data.items() if key=="STL"]
blk = [value for data in stats_data["Lakers"]for key, value in data.items() if key=="BLK"]
mfg = [value for data in stats_data["Lakers"]for key, value in data.items() if key=="FGM"]
mft = [value for data in stats_data["Lakers"]for key, value in data.items() if key=="FTM"]
tov = [value for data in stats_data["Lakers"]for key, value in data.items() if key=="TO"]

In [70]:
# Convert all python lists into Numpy arrays

lakers_height_array = np.array(lakers_height)
lakers_weight_array = np.array(lakers_weight)
pts_array = np.array(pts)
reb_array = np.array(reb)
ast_array = np.array(ast)
stl_array = np.array(stl)
blk_array = np.array(blk)
mfg_array = np.array(mfg)
mft_array = np.array(mft)
tov_array = np.array(tov)

In [71]:
example_2d = [[1,1,1],[1,1,1]]
print(np.array(example_2d))

[[1 1 1]
 [1 1 1]]


In [72]:
# Convert imperial data to metrics 

# Convert pounds to kilograms

lakers_weight_kg = lakers_weight_array * 0.454

# Convert inches to centimeters 

lakers_height_cm = lakers_height_array * 2.54

In [73]:
# BMI Calculator 
# system parameter is a string that states whether metric or imperial system
# metric (cm & kg)
# imperial (in & lbs)

def bmi_calculator(system, weight, height):
    """
    This function calculates the BMI of NBA players using either the metric system or the imperial system
    """
    BMI=None
    if system == "imperial":
        BMI = weight/(height**2)*703
    
    elif system == "metric":
        BMI = weight/(height**2)*10000
    return BMI


In [74]:
bmi_calculator("imperial", lakers_weight_array, lakers_height_array)

array([23.74554325, 24.82894737, 24.8430309 , 26.78707514, 26.45136823])

In [75]:
bmi_calculator("metric", lakers_weight_kg, lakers_height_cm)

array([23.769235  , 24.85372007, 24.86781765, 26.81380153, 26.47775968])

In [76]:
# Get BMI for Warriors 

In [77]:
# Store the weights and heights into python lists

gsw_height = [value for data in bmi_data["Golden State Warriors"] for key, value in data.items() if key=="Height"]
gsw_weight = [value for data in bmi_data["Golden State Warriors"] for key, value in data.items() if key=="Weight"]


# Convert list to Numpy arrays 

gsw_height_array = np.array(gsw_height)
gsw_weight_array = np.array(gsw_weight)

In [78]:
# Convert imperial data to metrics 

gsw_weight_kg = gsw_weight_array * 0.454
gsw_height_cm = gsw_height_array * 2.54

# Calculate BMI

print(bmi_calculator("imperial", gsw_weight_array, gsw_height_array))
print(bmi_calculator("metric", gsw_weight_kg, gsw_height_cm))

[23.75       25.42077581 22.19051434 26.57626561 23.78692273]
[23.7736962  25.44613899 22.21265458 26.60278167 23.81065576]


### Calculate the Lakers player efficiency rates with Numpy

(EFF) = (PTS + REB + AST + STL + BLK - MISSED FG - MISSED FT - TO)

* PTS - number of points scored by player
* REB - number of rebounds by player
* AST - number of assists 
* STL - number of steals 
* BLK - number of blocks 
* MISSED FG - number of missed field goals 
* MISSED FT - number of missed free throws
* TO - number of turn overs

In [79]:
# Calculating player effciency 

# (EFF) = (PTS + REB + AST + STL + BLK - MISSED FG - MISSED FT - TO)

lakers_player_efficiency = pts_array + reb_array + ast_array + stl_array + blk_array - mfg_array - mft_array - tov_array

In [81]:
# Player efficiency (higher = better)

print(lakers_player_efficiency)

[ 791  689  411 1776 1105]


### Calculate the Warriors starting five player efficiency rates

In [86]:
# Get GSW player stats

pts = [value for data in stats_data["Golden State Warriors"]for key, value in data.items() if key=="PTS"]
reb = [value for data in stats_data["Golden State Warriors"]for key, value in data.items() if key=="REB"]
ast = [value for data in stats_data["Golden State Warriors"]for key, value in data.items() if key=="AST"]
stl = [value for data in stats_data["Golden State Warriors"]for key, value in data.items() if key=="STL"]
blk = [value for data in stats_data["Golden State Warriors"]for key, value in data.items() if key=="BLK"]
mfg = [value for data in stats_data["Golden State Warriors"]for key, value in data.items() if key=="FGM"]
mft = [value for data in stats_data["Golden State Warriors"]for key, value in data.items() if key=="FTM"]
tov = [value for data in stats_data["Golden State Warriors"]for key, value in data.items() if key=="TO"]

In [87]:
# Convert to arrays 

pts_array = np.array(pts)
reb_array = np.array(reb)
ast_array = np.array(ast)
stl_array = np.array(stl)
blk_array = np.array(blk)
mfg_array = np.array(mfg)
mft_array = np.array(mft)
tov_array = np.array(tov)

In [88]:
# Calculating GSW startng five efficiency 

gsw_player_efficiency = pts_array + reb_array + ast_array + stl_array + blk_array - mfg_array - mft_array - tov_array
print(gsw_player_efficiency)

[1559  523 1128  821 1081]


### Aggregate Functions Lakers

In [89]:
# Performing aggregate functions on Lakers starting five

In [90]:
# Summation 

print(np.sum(lakers_height_array))

390


In [91]:
print(np.sum(lakers_weight_array))

1102


In [93]:
# Average height and weight for Lakers starting five 

print(np.average(lakers_height_array))

print(np.average(lakers_weight_array))

78.0
220.4


In [107]:
# Minimum and maximum height and weight 

print(np.min(lakers_height_array))
print(np.max(lakers_height_array))

print(np.min(lakers_weight_array))
print(np.max(lakers_weight_array))

73
82
180
253


In [95]:
# Caluculate the standard deviation 

print(lakers_weight_array.std())

print(lakers_height_array.std())

27.817979797246238
3.286335345030997


In [96]:
# Percentile for height

print(np.percentile(lakers_height_array, 50)) # looking at 50th percentile

print(np.percentile(lakers_height_array, 75)) # looking at 75th percentile

print(np.percentile(lakers_height_array, 90)) # looking at 90th percentile

78.0
81.0
81.6


In [97]:
# Percentile for weight 

print(np.percentile(lakers_weight_array, 50)) # looking at 50th percentile

print(np.percentile(lakers_weight_array, 75)) # looking at 75th percentile

print(np.percentile(lakers_weight_array, 90)) # looking at 90th percentile

215.0
250.0
251.8


### Aggregate Functions Warriors

In [98]:
# Summation of GSW height and weight 

print(np.sum(gsw_height_array))

print(np.sum(gsw_weight_array))

390
1054


In [99]:
# Average for GSW height and weight 

print(np.average(gsw_height_array))

print(np.average(gsw_weight_array))

78.0
210.8


In [106]:
# Min and max of GSW height and weight 

print(np.min(gsw_height_array))
print(np.max(gsw_height_array))

print(np.min(gsw_weight_array))
print(np.max(gsw_weight_array))

74
81
185
230


In [103]:
# Standard deviation for height and weight 

print(np.std(gsw_height_array))

print(np.std(gsw_weight_array))

2.280350850198276
16.939893742287758


In [105]:
# Percentile for GSW height and weight 

print(np.percentile(gsw_height_array, 25))
print(np.percentile(gsw_height_array, 50))
print(np.percentile(gsw_height_array, 75))

print(np.percentile(gsw_weight_array, 25))
print(np.percentile(gsw_weight_array, 50))
print(np.percentile(gsw_weight_array, 75))

78.0
78.0
79.0
197.0
220.0
222.0


### Calculate the efficiency of the top 10 highest paid players

In [110]:
# Get the BMI data for the top 10 highest paid players 

top10_height = [value for data in bmi_data["Top 10 Highest Paid NBA Players"]for key, value in data.items() if key=="Height"]
top10_weight = [value for data in bmi_data["Top 10 Highest Paid NBA Players"]for key, value in data.items() if key=="Weight"]

In [111]:
# Get the stats data of the 10 highest paid players 

pts = [value for data in stats_data["Top 10 Highest Paid NBA Players"]for key, value in data.items() if key=="PTS"]
reb = [value for data in stats_data["Top 10 Highest Paid NBA Players"]for key, value in data.items() if key=="REB"]
ast = [value for data in stats_data["Top 10 Highest Paid NBA Players"]for key, value in data.items() if key=="AST"]
stl = [value for data in stats_data["Top 10 Highest Paid NBA Players"]for key, value in data.items() if key=="STL"]
blk = [value for data in stats_data["Top 10 Highest Paid NBA Players"]for key, value in data.items() if key=="BLK"]
mfg = [value for data in stats_data["Top 10 Highest Paid NBA Players"]for key, value in data.items() if key=="FGM"]
mft = [value for data in stats_data["Top 10 Highest Paid NBA Players"]for key, value in data.items() if key=="FTM"]
tov = [value for data in stats_data["Top 10 Highest Paid NBA Players"]for key, value in data.items() if key=="TO"]

In [123]:
# Convert to arrays 

top10_height_array = np.array(top10_height)
top10_weight_array = np.array(top10_weight)
pts_array = np.array(pts)
reb_array = np.array(reb)
ast_array = np.array(ast)
stl_array = np.array(stl)
blk_array = np.array(blk)
mfg_array = np.array(mfg)
mft_array = np.array(mft)
tov_array = np.array(tov)

print("Players")
print([value for data in stats_data["Top 10 Highest Paid NBA Players"]for key, value in data.items() if key=="Name"])
print("")

# Convert pounds to kilograms 
top10_weight_kg = top10_weight_array * 0.454

# Convert height from inches to cm 
top10_height_cm = top10_height_array * 2.54


# Calculate BMI
print("Imperial BMI in Order")
print(bmi_calculator("imperial", top10_weight_array, top10_height_array))
print("")
print("Metric BMI in Order")
print(bmi_calculator("metric", top10_weight_kg, top10_height_cm))



# Player efficiency 
top10_players_efficiency = pts_array + reb_array + ast_array + stl_array + blk_array - mfg_array - mft_array - tov_array
print("Player Efficiency in Order")
print(top10_players_efficiency)

Players
['Lebron James', 'Russell Westbrook', 'Kevin Durant', 'James Harden', 'Stephen Curry', 'Damian Lillard', 'Paul George', 'Giannis Antetokounmpo', 'Klay Thompson']

Imperial BMI in Order
[26.78707514 24.99555556 25.09220702 26.08534323 23.75       24.90540541
 24.165625   24.79735811 25.42077581]

Metric BMI in Order
[26.81380153 25.02049449 25.11724238 26.11136948 23.7736962  24.93025439
 24.18973588 24.82209929 25.44613899]
Player Efficiency in Order
[1776 1553 1804 1782 1559  620  708 2343  523]
